# Generated by Django 5.2.3 on 2025-07-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('anel', 'Anel'), ('colar', 'Colar'), ('pulseira', 'Pulseira'), ('brinco', 'Brinco'), ('outro', 'Outro')], default='outro', max_length=20),
            preserve_default=False,
        ),
    ]
